version: '3.2'
services:
  cdss-mysql:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"

  cdss-app:
    image:
      registry.gitlab.com/pvandermerwe/cdss-supplier-stub:latest
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://cdss-mysql:3306/cdss_supplier
    ports: 
      - "8080:8080"
    restart: on-failure:5