package uk.nhs.cdss.rules.palpitations

import uk.nhs.cdss.rules.InitialQuestionnaire
import uk.nhs.cdss.rules.QuestionFlow
import uk.nhs.cdss.rules.AnswerAssertion

import uk.nhs.cdss.domain.Answer
import uk.nhs.cdss.domain.Assertion
import uk.nhs.cdss.domain.Assertion.Status
import uk.nhs.cdss.domain.CarePlan
import uk.nhs.cdss.domain.CodableConcept
import uk.nhs.cdss.domain.Questionnaire

import uk.nhs.cdss.engine.CodeDirectory

global CodeDirectory codeDirectory;

rule "Init"
when
    eval( true )
then
    // Questions
    insert( new InitialQuestionnaire("palpitations.chestPain") );
    insert( new QuestionFlow("palpitations.chestPain", "palpitations.neckPain") );
    insert( new QuestionFlow("palpitations.neckPain", "palpitations.breathing") );
    insert( new QuestionFlow("palpitations.breathing", "palpitations.heartProblems") );

    // Assertions
    insert( new AnswerAssertion("palpitations.chestPain", "q1", "Yes", codeDirectory.get("chestPain"), true));
    insert( new AnswerAssertion("palpitations.chestPain", "q1", "No", codeDirectory.get("chestPain"), false));

    insert( new AnswerAssertion("palpitations.neckPain", "q2", "Yes", codeDirectory.get("neckPain"), true));
    insert( new AnswerAssertion("palpitations.neckPain", "q2", "No", codeDirectory.get("neckPain"), false));

    insert( new AnswerAssertion("palpitations.breathing", "q3", "Yes", codeDirectory.get("breathingProblems"), true));
    insert( new AnswerAssertion("palpitations.breathing", "q3", "No", codeDirectory.get("breathingProblems"), false));

    insert( new AnswerAssertion("palpitations.heartProblems", "q4", "Yes", codeDirectory.get("heartProblems"), true));
    insert( new AnswerAssertion("palpitations.heartProblems", "q4", "No", codeDirectory.get("heartProblems"), false));
end

// Results
rule "Any symptoms"
salience 30
when
    $a: Assertion( value == true )
then
    System.out.println("Assertion present: " + $a);
    System.out.println("Directing to 999");
    insert( new CarePlan("call999") );
end

rule "No symptoms"
when
    not Assertion( value == true )
    not Questionnaire()
then
    System.out.println("Patient did not answer 'Yes' to any questions");
    System.out.println("Directing to self care");
    insert( new CarePlan("selfCare") );
end