package uk.nhs.cdss.rules.anxiety

import java.util.Arrays

import uk.nhs.cdss.rules.InitialQuestionnaire
import uk.nhs.cdss.rules.AnswerAssertion
import uk.nhs.cdss.rules.OutcomeAnswerCondition

import uk.nhs.cdss.domain.Outcome
import uk.nhs.cdss.domain.ReferralRequest

import uk.nhs.cdss.engine.CodeDirectory

global CodeDirectory codeDirectory;

rule "Init"
when
then
    insert( new InitialQuestionnaire("anxiety.anxiety") );
    insert( new AnswerAssertion("anxiety.anxiety", "q", "Yes", codeDirectory.get("anxiety"), true));
    insert( Outcome.of("anxiety",
        ReferralRequest.builder()
            .id("gp-anxiety-72h")
            .description("Consult GP")
            .occurrence("PT72h")
            .specialty("gp")
            .reason("anxiety")
            .note("A note")
            .build()));
    insert( new OutcomeAnswerCondition("anxiety", "anxiety.anxiety", "q", Arrays.asList("Yes", "No") ));
end