package uk.nhs.cdss.rules.anxiety

import java.util.Arrays

import uk.nhs.cdss.rules.InitialQuestionnaire
import uk.nhs.cdss.rules.AnswerAssertion
import uk.nhs.cdss.rules.OutcomeAnswerCondition

import uk.nhs.cdss.domain.Outcome

import uk.nhs.cdss.engine.CodeDirectory

global CodeDirectory codeDirectory;

rule "Init"
when
    eval( true )
then
    insert( new InitialQuestionnaire("anxiety.anxiety") );

    insert( new AnswerAssertion("anxiety.anxiety", "q", "Yes", codeDirectory.get("anxiety"), true));
    insert( new AnswerAssertion("anxiety.anxiety", "q", "No", codeDirectory.get("anxiety"), false));

    insert( Outcome.referralRequest("anxiety", "consultGP-anxiety"));
    insert( new OutcomeAnswerCondition("anxiety", "anxiety.anxiety", "q", Arrays.asList("Yes", "No") ));
end