package uk.nhs.cdss.rules.initial

import java.util.Arrays

import uk.nhs.cdss.rules.InitialQuestionnaire
import uk.nhs.cdss.rules.AnswerAssertion
import uk.nhs.cdss.rules.OutcomeAnswerCondition

import uk.nhs.cdss.domain.Outcome
import uk.nhs.cdss.domain.ReferralRequest
import uk.nhs.cdss.domain.Redirection

import uk.nhs.cdss.engine.CodeDirectory
import uk.nhs.cdss.domain.Concept

global CodeDirectory codeDirectory;

function Outcome singleCodeRedirection(String id, String code) {
    return Outcome.of(id, Redirection.builder()
            .id(code)
            .code(code)
            .build());
}

rule "Init"
when
then
    insert( new InitialQuestionnaire("initial.initial") );

    Concept present = codeDirectory.get("present");
    insert( new AnswerAssertion("initial.initial", "q", "chestPain", codeDirectory.get("chestPain"), true));
    insert( new AnswerAssertion("initial.initial", "q", "palpitations", codeDirectory.get("palpitations"), true));
    insert( new AnswerAssertion("initial.initial", "q", "genitoUrinaryProblems", codeDirectory.get("genitoUrinaryProblems"), true));

    insert( new AnswerAssertion("initial.initial", "q", "constipation", codeDirectory.get("constipation"), present));
    insert( new AnswerAssertion("initial.initial", "q", "soreThroat", codeDirectory.get("soreThroat"), present));

    // These redirections are not dependent on context
    insert( singleCodeRedirection("chestPain", "chestPain"));
    insert( new OutcomeAnswerCondition("chestPain", "initial.initial", "q", Arrays.asList("chestPain") ));
    insert( singleCodeRedirection("palpitations", "palpitations"));
    insert( new OutcomeAnswerCondition("palpitations", "initial.initial", "q", Arrays.asList("palpitations") ));

    // This is a complex trigger with additional gender context requirement
    // FIXME it will fail to match if the gender of the patient is incorrect
    insert( Outcome.of("genitoUrinaryProblems", Redirection.builder()
            .id("genitoUrinaryProblems")
            .code("genitoUrinaryProblems")
            .code("isFemale")
            .build()) );
    insert( new OutcomeAnswerCondition("genitoUrinaryProblems", "initial.initial", "q", Arrays.asList("genitoUrinaryProblems") ));

    // These redirections are to service definitions with context-dependent triggers.
    insert( Outcome.of("constipation", Redirection.builder()
                        .id("constipation")
                        .code("constipation")
                        .code("lifeThreatening")
                        .build()) );
    insert( new OutcomeAnswerCondition("constipation", "initial.initial", "q", Arrays.asList("constipation") ));
    insert( Outcome.of("soreThroat", Redirection.builder()
                        .id("soreThroat")
                        .code("soreThroat")
                        .code("lifeThreatening")
                        .build()) );
    insert( new OutcomeAnswerCondition("soreThroat", "initial.initial", "q", Arrays.asList("soreThroat") ));
end