package uk.nhs.cdss.rules.initial

import java.util.Arrays

import uk.nhs.cdss.rules.InitialQuestionnaire
import uk.nhs.cdss.rules.AnswerAssertion
import uk.nhs.cdss.rules.OutcomeAnswerCondition

import uk.nhs.cdss.domain.Outcome
import uk.nhs.cdss.domain.ReferralRequest
import uk.nhs.cdss.domain.Redirection

import uk.nhs.cdss.engine.CodeDirectory

global CodeDirectory codeDirectory;

function Outcome singleCodeRedirection(String id, String code) {
    return Outcome.of(id, Redirection.builder()
            .id(code)
            .code(code)
            .build());
}

rule "Init"
when
then
    insert( new InitialQuestionnaire("initial.initial") );

    insert( new AnswerAssertion("initial.initial", "q", "chestPain", codeDirectory.get("chestPain"), true));
    insert( new AnswerAssertion("initial.initial", "q", "palpitations", codeDirectory.get("palpitations"), true));
    insert( new AnswerAssertion("initial.initial", "q", "genitoUrinaryProblems", codeDirectory.get("genitoUrinaryProblems"), true));

    insert( singleCodeRedirection("chestPain", "chestPain"));
    insert( new OutcomeAnswerCondition("chestPain", "initial.initial", "q", Arrays.asList("chestPain") ));

    insert( singleCodeRedirection("palpitations", "palpitations"));
    insert( new OutcomeAnswerCondition("palpitations", "initial.initial", "q", Arrays.asList("palpitations") ));

    insert( Outcome.of("genitoUrinaryProblems", Redirection.builder()
            .id("genitoUrinaryProblems")
            .code("genitoUrinaryProblems")
            .code("isFemale")
            .build()) );
    insert( new OutcomeAnswerCondition("genitoUrinaryProblems", "initial.initial", "q", Arrays.asList("genitoUrinaryProblems") ));

end