package uk.nhs.cdss.rules.palpitations

import java.util.Arrays

import uk.nhs.cdss.rules.InitialQuestionnaire
import uk.nhs.cdss.rules.AnswerAssertion
import uk.nhs.cdss.rules.OutcomeAnswerCondition

import uk.nhs.cdss.domain.Questionnaire
import uk.nhs.cdss.domain.Outcome
import uk.nhs.cdss.domain.ReferralRequest

import uk.nhs.cdss.engine.CodeDirectory

global CodeDirectory codeDirectory;

rule "Init"
salience 10000
when
    eval( true )
then
    insert( new InitialQuestionnaire("musculoskeletal.musculoskeletal") );
    insert( new AnswerAssertion("musculoskeletal.musculoskeletal", "q", "Yes", codeDirectory.get("musculoskeletal"), true));
    insert( new AnswerAssertion("musculoskeletal.musculoskeletal", "q", "No", codeDirectory.get("musculoskeletal"), false));
    insert(  Outcome.of("musculoskeletal",
        ReferralRequest.builder()
            .id("musculoskeletal")
            .description("PLACEHOLDER REFERRAL")
            .serviceRequested("call999")
            .occurrence("PT8m")
            .specialty("cardio")
            .reason("ami")
            .note("A note")
            .build())); //Temporary - this is not the right outcome
    insert( new OutcomeAnswerCondition("musculoskeletal", "musculoskeletal.musculoskeletal", "q", Arrays.asList("Yes", "No") ));
end