package uk.nhs.cdss.engine;

import uk.nhs.cdss.exception.ServiceDefinitionException;

public interface CDSEngine {

  /**
   * @param input The input for the service definition
   * @return the output generated by evaluating the service definition
   * @throws ServiceDefinitionException when the requested service definition cannot be evaluated
   */
  CDSOutput evaluate(CDSInput input) throws ServiceDefinitionException;
}
